import { Inter } from "next/font/google";
import Footer from "../../components/Footer";
import Header from "../../components/Header";
import "./globals.css";
import Providers from "./providers";
import { Children } from "react";
import Navbar from "../../components/Navbar";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Straw Hats",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <Providers>
           <Header /> 
           <Navbar />
           {children}
           <Footer />
         </Providers>
      </body>
    </html>
  );
}
